package io.github.colemakmods.keyboard;

import java.util.List;

/**
 * Holder for all the output results generated by the keyboard layout analyzer
 *
 * Created by steve on 12/01/18.
 */
public class LayoutResults {
    private KeyboardLayout keyboardLayout;
    private List<String> messages;
    private double[] fingerFreq;
    private double handAlternation;
    private List<FingerBigram> sameFingerBigrams;
    private List<FingerBigram> neighbourFingerBigrams;
    private double[][] fingerEffort;

    public LayoutResults(KeyboardLayout keyboardLayout, List<String> messages,
                         double[] fingerFreq, double handAlternation,
                         List<FingerBigram> sameFingerBigrams, List<FingerBigram> neighbourFingerBigrams,
                         double[][] fingerEffort) {
        this.keyboardLayout = keyboardLayout;
        this.messages = messages;
        this.fingerFreq = fingerFreq;
        this.handAlternation = handAlternation;
        this.sameFingerBigrams = sameFingerBigrams;
        this.neighbourFingerBigrams = neighbourFingerBigrams;
        this.fingerEffort = fingerEffort;
    }

    public KeyboardLayout getLayout() {
        return keyboardLayout;
    }

    public List<String> getMessages() {
        return messages;
    }

    public double[] getFingerFreq() {
        return fingerFreq;
    }

    public double getHandAlternation() {
        return handAlternation;
    }

    public List<FingerBigram> getSameFingerBigrams() {
        return sameFingerBigrams;
    }

    public List<FingerBigram> getNeighbourFingerBigrams() {
        return neighbourFingerBigrams;
    }

    public double[][] getFingerEffort() {
        return fingerEffort;
    }


}
